### ISSUE TITLE
Rename `master` to `main`

### ISSUE THREAD

**Issue by asbjornu** [reviewdog/action-remark-lint#48]
For consistency with the rest of the community and to avoid the negative baggage associated with `master`, I suggest we [rename `master` to `main`](https://github.com/github/renaming#renaming-the-default-branch-from-master). Before this can happen, `master` needs to be replaced with `main` in the following places: 

https://github.com/reviewdog/action-remark-lint/blob/e16cd952fa1e8d24f95e3aee266fbd55e1470b0a/.github/workflows/depup.yml#L32

https://github.com/reviewdog/action-remark-lint/blob/e16cd952fa1e8d24f95e3aee266fbd55e1470b0a/.github/workflows/dockerimage.yml#L5

https://github.com/reviewdog/action-remark-lint/blob/e16cd952fa1e8d24f95e3aee266fbd55e1470b0a/.github/workflows/release.yml#L5

https://github.com/reviewdog/action-remark-lint/blob/e16cd952fa1e8d24f95e3aee266fbd55e1470b0a/.github/workflows/reviewdog.yml#L5

https://github.com/reviewdog/action-remark-lint/blob/e16cd952fa1e8d24f95e3aee266fbd55e1470b0a/.github/workflows/test.yml#L5

**Comment by rickstaa** [comment]
@asbjornu Looks good to me, since GitHub internally now also uses main as the default branch (see https://github.com/github/renaming). I know this is a sensitive topic and understand that some people might disagree with GitHub's decision, but I see no harm in merging #49 under v4. 

If somebody has a good argument, why #49 should not be merged, feel free to comment on this topic. I will merge #49 this weekend.

**Comment by rickstaa** [comment]
This issue will be closed by #53 and #52. Before these can be merged, the default branch has to be changed.

**Comment by rickstaa** [comment]
This was implemented in https://github.com/reviewdog/action-remark-lint/releases/tag/v4.0.0.
